<a href="<?=App::config('url')?>prodavac/novi"
    class="success button expanded">Dodaj prodavača</a>

<table>
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Email</th>
            <th>OIB</th>
            <th>IBAN</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($prodavac as $p): ?>
            <tr>
                <td><?=$p->ime?></td>
                <td><?=$p->prezime?></td>
                <td><?=$p->email?></td>
                <td><?=$p->OIB?></td>
                <td><?=$p->IBAN?></td>
                <td>
                    <a href="<?=App::config('url')?>prodavac/promjena/<?=$p->sifra?>">
                        <i style="color: blue;" 
                        class="step fi-pencil size-36"></i>
                    </a>
                    &nbsp;&nbsp;
                    <?php if($p->racuna==0): ?>
                    <a href="<?=App::config('url')?>prodavac/brisanje/<?=$p->sifra?>">
                        <i style="color: red;" 
                        class="step fi-page-delete size-36"></i>
                     </a>
                     <?php else: ?>
                        <i style="color: gray;" title="Prodavač se ne može obrisati jer se nalazi na nekom računu"
                        class="step fi-page-delete size-36"></i>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>