<a href="<?=App::config('url')?>bicikl/novi"
    class="success button expanded">Dodaj novi bicikl</a>

<table>
    <thead>
        <tr>
            <th>Proizvođač</th>
            <th>Namjena</th>
            <th>Električni</th>
            <th>Broj brzina</th>
            <th>Veličina (cm)</th>
            <th>Cijena (kn)</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($bicikl as $b): ?>
            <tr>
                <td><?=$b->proizvodac?></td>
                <td><?=$b->namjena?></td>
                <td>
                    <i style="color: <?php echo $b->elektricni ? 'green' : 'red';  ?>;" 
                        class="step <?php echo $b->elektricni ? 'fi-battery-full' : 'fi-x' ?> size-48">
                </td>
                <td><?=$b->broj_brzina?></td>
                <td><?=$b->velicina_cm?></td>
                <td><?=$b->cijena_kn?>kn (<?=round((float)$b->cijena_kn/7.5345, 2)?>€)</td>
                <td>
                    <a href="<?=App::config('url')?>bicikl/promjena/<?=$b->sifra?>">
                        <i style="color: blue;" 
                        class="step fi-pencil size-36"></i>
                    </a>
                    &nbsp;&nbsp;
                    <?php if($b->racuna==0): ?>
                    <a href="<?=App::config('url')?>bicikl/brisanje/<?=$b->sifra?>">
                        <i style="color: red;" title="Obriši bicikl" 
                        class="step fi-page-delete size-36"></i>
                    </a>
                    <?php else: ?>
                        <i style="color: gray;" title="Bicikl se ne može obrisati jer je u košarici ili računu"
                        class="step fi-page-delete size-36"></i>
                    <?php endif; ?>
                    <!-- Košarica -->
                    <!-- &nbsp;&nbsp;
                    <a href="<?=App::config('url')?>bicikl/ukošaricu/<?=$b->sifra?>">
                        <i style= "color: darkgreen;"
                            class="step fi-shopping-cart size-36"></i>
                    </a>  -->
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>