<table>
    <thead>
        <tr>
            <th>Proizvodac</th>
            <th>Namjena</th>
            <th>Elektricni</th>
            <th>Broj brzina</th>
            <th>Velicina (cm)</th>
            <th>Cijena (kn)</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($bicikl as $b): ?>
            <tr>
                <td><?=$b->proizvodac?></td>
                <td><?=$b->namjena?></td>
                <td><?=$b->elektricni?></td>
                <td><?=$b->broj_brzina?></td>
                <td><?=$b->velicina_cm?></td>
                <td><?=$b->cijena_kn?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>