<a href="<?=App::config('url')?>bicikl/novi"
    class="success button expanded">Dodaj novi bicikl</a>

<table>
    <thead>
        <tr>
            <th>Proizvođač</th>
            <th>Namjena</th>
            <th>Električni</th>
            <th>Broj brzina</th>
            <th>Veličina (cm)</th>
            <th>Cijena (kn)</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($bicikl as $b): ?>
            <tr>
                <td><?=$b->proizvodac?></td>
                <td><?=$b->namjena?></td>
                <td>
                    <i style="color: <?php echo $b->elektricni ? 'green' : 'red';  ?>;" 
                        class="step <?php echo $b->elektricni ? 'fi-check' : 'fi-x' ?> size-48">
                </td>
                <td><?=$b->broj_brzina?></td>
                <td><?=$b->velicina_cm?></td>
                <td><?=$b->cijena_kn?>kn (<?=round((float)$b->cijena_kn/7.5345, 2)?>€)</td>
                <td>
                    <a href="<?=App::config('url')?>bicikl/promjena/<?=$b->sifra?>">
                        <i style="color: blue;" 
                        class="step fi-pencil size-36"></i>
                     </a>
                        <!-- Loš način --> &nbsp;&nbsp;<!-- bolji način CSS margin-right -->
                     <a href="<?=App::config('url')?>bicikl/brisanje/<?=$b->sifra?>">
                        <i style="color: red;" 
                        class="step fi-page-delete size-36"></i>
                     </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>