<a href="<?=App::config('url')?>stavka/novi"
    class="success button expanded">Dodaj novi</a>

    <table>
    <thead>
        <tr>
            <th>Bicikl</th>
            <th>Kolicina</th>
            <th>Cijena</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($stavka as $s): ?>
            <tr>
                <td><?=$s->proizvodac?></td>
                <td><?=$s->kolicina?></td>
                <td><?=$s->cijena_kn?></td>
                <td>
                    <a href="<?=App::config('url')?>stavka/promjena/<?=$s->sifra?>">
                        <i style="color: blue;" 
                        class="step fi-pencil size-36"></i>
                    </a>
                        <!-- Loš način --> &nbsp;&nbsp;<!-- bolji način CSS margin-right -->
                    <a href="<?=App::config('url')?>stavka/brisanje/<?=$s->sifra?>">
                        <i style="color: red;" 
                        class="step fi-page-delete size-36"></i>
                     </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>