<form method="post" 
action="<?=App::config('url')?>kupac/novi">
  <h4 class="text-center">Dodavanje novog kupca</h4>
  <label>Ime
    <input type="text" name="ime" value="<?=$kupac->ime?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime" value="<?=$kupac->prezime?>" />
  </label>

  <label>mobitel
    <input type="number" name="OIB" value="<?=$kupac->mobitel?>" />
  </label>

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>kupac">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Dodaj"></input>
    </div>
  </div>


</form>


