<form method="post" 
action="<?=App::config('url')?>kupac/brisanje/<?=$kupac->sifra?>">
  <h4 class="text-center">Brisanje kupca</h4>
  <label>Ime
    <input disabled="disabled" type="text" name="ime" value="<?=$kupac->ime?>" />
  </label>

  <label>Prezime
    <input disabled="disabled" type="text" name="prezime" value="<?=$kupac->prezime?>" />
  </label>

  <label>email
    <input disabled="disabled" type="number" name="mobitel" value="<?=$kupac->mobitel?>" />
  </label>

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>kupac">Odustani</a>
    </div>
    <div class="large-6 cell">
    <?php if($brisanje): ?>
            <input type="hidden" name="obrisi" value="true" />
            <input type="submit" class="button expanded" value="Obriši" />
        <?php else: ?>
            Kupac se ne može obrisati
        <?php endif; ?>
    </div>
  </div>


</form>


