<a href="<?=App::config('url')?>racun/novi"
    class="success button expanded">Dodaj novi</a>


<div class="grid-x grid-padding-x">
    <?php foreach($racun as $r):?>
        <div class="large-6 cell">
            <div class="callout" style="display: flex; justify-content: space-around;">
                <div>
                slika
                </div>
                <div>
                    <h1 style="font-size: 1.5rem;"> <?=$r->proizvodac?></h1>
                        Ime prodavača: <?=$r->ime_prodavaca?> <br>
                        Ime kupca: <?=$r->ime_kupca?> <br>
                        Vrijeme kupnje: <?=$r->vrijeme_kupnje?> <br>
                        Cijena (jednog): <?=$r->cijena_kn?>kn (<?=round($r->cijena_kn/7.5345, 2)?>€) <br>
                        Količina: <?=$r->kolicina?> <br>
                        Ukupna cijena: <?=$r->cijena_kn*$r->kolicina?>kn (<?=round($r->cijena_kn*$r->kolicina/7.5345, 2)?>€)
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>