<label for="bicikl">Bicikl</label>
<select name="bicikl" id="bicikl">
    <?php foreach($bicikli as $b): ?>
        <option
        <?php if ($e->bicikl==$b->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$b->sifra?>"><?=$b->proizvodac?></option>
    <?php endforeach; ?>
</select>

<label>Količina
    <input type="number" name="kolicina" value="<?=$kolicina?>" />
</label>
  
<label for="vrijeme_kupnje">Datum kupnje</label>
  <input type="date" name="vrijeme_kupnje" id="vrijeme_kupnje" 
value="<?=$vrijeme_kupnje?>" lang="hr-HR">

  <label for="prodavac">Prodavač</label>
<select name="prodavac" id="prodavac">
    <?php foreach($prodavaci as $p): ?>
        <option
        <?php if ($e->prodavac==$p->sifra){
            echo 'selected="selected"';
        }
        ?>
        value="<?=$p->sifra?>"><?=$p->ime?> <?=$p->prezime?></option>
    <?php endforeach; ?>
</select>


<label for="kupac">Kupac</label>
<select name="kupac" id="kupac">
    <?php foreach($kupci as $k): ?>
        <option
        <?php if ($e->kupac==$k->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$k->sifra?>"><?=$k->ime?> <?=$k->prezime?></option>
    <?php endforeach; ?>
</select>