<a href="<?=App::config('url')?>racun/novi"
    class="success button expanded">Dodaj novi</a>

    <table>
    <thead>
        <tr>
            <th>Vrijeme kupnje</th>
            <th>Prodavac</th>
            <th>Kupac</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($racun as $r): ?>
            <tr>
                <td><?=$r->vrijeme_kupnje?></td>
                <td><?=$r->prodavac?></td>
                <td><?=$r->kupac?></td>
                <td>
                    <a href="<?=App::config('url')?>racun/promjena/<?=$r->sifra?>">
                        <i style="color: blue;" 
                        class="step fi-pencil size-36"></i>
                    </a>
                        <!-- Loš način --> &nbsp;&nbsp;<!-- bolji način CSS margin-right -->
                    <a href="<?=App::config('url')?>racun/brisanje/<?=$r->sifra?>">
                        <i style="color: red;" 
                        class="step fi-page-delete size-36"></i>
                     </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>