<a href="<?=App::config('url')?>racun/novi"
    class="success button expanded">Dodaj novi račun</a>

    <table>
    <thead>
        <tr>
            <th>Bicikl</th>
            <th>Ime p</th>
            <th>Prezime p</th>
            <th>Ime k</th>
            <th>Vrijeme kupnje</th>
            <th>Cijena</th>
            <th>Količina</th>
            <th>Ukupna cijena</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($racun as $r): ?>
            <tr>
                <td><?=$r->proizvodac?></td>
                <td><?=$r->ime_prodavaca?></td>
                <td><?=$r->prezime_prodavaca?></td>
                <td><?=$r->ime_kupca?></td>
                <td><?=$r->vrijeme_kupnje?></td>
                <td><?=$r->cijena_kn?>kn (<?=round($r->cijena_kn/7.5345, 2)?>€)</td>
                <td><?=$r->kolicina?></td>
                <td><?=$r->cijena_kn*$r->kolicina?>kn (<?=round($r->cijena_kn*$r->kolicina/7.5345, 2)?>€)</td>
                <td>
                    <a href="<?=App::config('url')?>racun/promjena/<?=$r->sifra?>">
                        <i style="color: blue;" 
                        class="step fi-pencil size-36"></i>
                    </a>
                        <!-- Loš način --> &nbsp;&nbsp;<!-- bolji način CSS margin-right -->
                    <a href="<?=App::config('url')?>racun/brisanje/<?=$r->sifra?>">
                        <i style="color: red;" 
                        class="step fi-page-delete size-36"></i>
                     </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>